### ISSUE TITLE
after generated the temp link  i cannot view that file from this link

### ISSUE THREAD

**Issue by skanel** [danilkozyrev/file-storage-api#1]
after I generated the tmp link of file example
`https://localhost:8443/links/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMDUxIiwiZXhwIjoxNjMyMDY3OTAxLCJpYXQiOjE2MzIwNDYzMDEsImp0aSI6IjYzOGZiNzI3LWVhMDctNDc1NC1iNzA2LTkxZTJiZGNhYWM2YSJ9.7YzptY0UYP6tLczIp9Q33ltWuAeVODnfmL7oMpPYa9s`

Then when I clicked on this link I got 

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sun Sep 19 17:13:04 ICT 2021
There was an unexpected error (type=Not Found, status=404).
No message available
```

**Comment by danilkozyrev** [comment]
Fixed in bce5564ef11a1fed0c83a71e2aac803ba7a8c44b.
